CREATE USER 'millan'@'%' IDENTIFIED WITH mysql_native_password AS '***';GRANT ALL PRIVILEGES ON *.* TO 'millan'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS `millan`;GRANT ALL PRIVILEGES ON `millan`.* TO 'millan'@'%';GRANT ALL PRIVILEGES ON `millan\_%`.* TO 'millan'@'%';


